/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitTreeDiff struct {
	// ObjectId of the base tree of this diff.
	BaseTreeId string `json:"baseTreeId,omitempty"`
	// List of tree entries that differ between the base and target tree.  Renames and object type changes are returned as a delete for the old object and add for the new object.  If a continuation token is returned in the response header, some tree entries are yet to be processed and may yeild more diff entries. If the continuation token is not returned all the diff entries have been included in this response.
	DiffEntries []GitTreeDiffEntry `json:"diffEntries,omitempty"`
	// ObjectId of the target tree of this diff.
	TargetTreeId string `json:"targetTreeId,omitempty"`
	// REST Url to this resource.
	Url string `json:"url,omitempty"`
}
