/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Data object for RenameRename conflict
type GitConflictRenameRename struct {
	Links *ReferenceLinks `json:"_links,omitempty"`
	ConflictId int32 `json:"conflictId,omitempty"`
	ConflictPath string `json:"conflictPath,omitempty"`
	ConflictType string `json:"conflictType,omitempty"`
	MergeBaseCommit *GitCommitRef `json:"mergeBaseCommit,omitempty"`
	MergeOrigin *GitMergeOriginRef `json:"mergeOrigin,omitempty"`
	MergeSourceCommit *GitCommitRef `json:"mergeSourceCommit,omitempty"`
	MergeTargetCommit *GitCommitRef `json:"mergeTargetCommit,omitempty"`
	ResolutionError string `json:"resolutionError,omitempty"`
	ResolutionStatus string `json:"resolutionStatus,omitempty"`
	ResolvedBy *IdentityRef `json:"resolvedBy,omitempty"`
	ResolvedDate time.Time `json:"resolvedDate,omitempty"`
	Url string `json:"url,omitempty"`
}
