/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Provides properties that describe a Git pull request iteration. Iterations are created as a result of creating and pushing updates to a pull request.
type GitPullRequestIteration struct {
	// A collection of related REST reference links.
	Links *ReferenceLinks `json:"_links,omitempty"`
	// Author of the pull request iteration.
	Author *IdentityRef `json:"author,omitempty"`
	// Changes included with the pull request iteration.
	ChangeList []GitPullRequestChange `json:"changeList,omitempty"`
	// The commits included with the pull request iteration.
	Commits []GitCommitRef `json:"commits,omitempty"`
	// The first common Git commit of the source and target refs.
	CommonRefCommit *GitCommitRef `json:"commonRefCommit,omitempty"`
	// The creation date of the pull request iteration.
	CreatedDate time.Time `json:"createdDate,omitempty"`
	// Description of the pull request iteration.
	Description string `json:"description,omitempty"`
	// Indicates if the Commits property contains a truncated list of commits in this pull request iteration.
	HasMoreCommits bool `json:"hasMoreCommits,omitempty"`
	// ID of the pull request iteration. Iterations are created as a result of creating and pushing updates to a pull request.
	Id int32 `json:"id,omitempty"`
	// If the iteration reason is Retarget, this is the refName of the new target
	NewTargetRefName string `json:"newTargetRefName,omitempty"`
	// The Git push information associated with this pull request iteration.
	Push *GitPushRef `json:"push,omitempty"`
	// The reason for which the pull request iteration was created.
	Reason string `json:"reason,omitempty"`
	// The source Git commit of this iteration.
	SourceRefCommit *GitCommitRef `json:"sourceRefCommit,omitempty"`
	// The target Git commit of this iteration.
	TargetRefCommit *GitCommitRef `json:"targetRefCommit,omitempty"`
	// The updated date of the pull request iteration.
	UpdatedDate time.Time `json:"updatedDate,omitempty"`
}
