/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitFilePathsCollection struct {
	CommitId string `json:"commitId,omitempty"`
	Paths []string `json:"paths,omitempty"`
	Url string `json:"url,omitempty"`
}
