/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type TfvcStatistics struct {
	// Id of the last changeset the stats are based on.
	ChangesetId int32 `json:"changesetId,omitempty"`
	// Count of files at the requested scope.
	FileCountTotal int64 `json:"fileCountTotal,omitempty"`
}
