/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// 
type ChangeList struct {
	AllChangesIncluded bool `json:"allChangesIncluded,omitempty"`
	ChangeCounts map[string]int32 `json:"changeCounts,omitempty"`
	Changes []Change `json:"changes,omitempty"`
	Comment string `json:"comment,omitempty"`
	CommentTruncated bool `json:"commentTruncated,omitempty"`
	CreationDate time.Time `json:"creationDate,omitempty"`
	Notes []CheckinNote `json:"notes,omitempty"`
	Owner string `json:"owner,omitempty"`
	OwnerDisplayName string `json:"ownerDisplayName,omitempty"`
	OwnerId string `json:"ownerId,omitempty"`
	SortDate time.Time `json:"sortDate,omitempty"`
	Version string `json:"version,omitempty"`
}
