/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitTemplate struct {
	// Name of the Template
	Name string `json:"name,omitempty"`
	// Type of the Template
	Type_ string `json:"type,omitempty"`
}
