/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Information about a fork ref.
type GitForkRef struct {
	Links *ReferenceLinks `json:"_links,omitempty"`
	Creator *IdentityRef `json:"creator,omitempty"`
	IsLocked bool `json:"isLocked,omitempty"`
	IsLockedBy *IdentityRef `json:"isLockedBy,omitempty"`
	Name string `json:"name,omitempty"`
	ObjectId string `json:"objectId,omitempty"`
	PeeledObjectId string `json:"peeledObjectId,omitempty"`
	Statuses []GitStatus `json:"statuses,omitempty"`
	Url string `json:"url,omitempty"`
}
