/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// 
type GitPush struct {
	Links *ReferenceLinks `json:"_links,omitempty"`
	Date time.Time `json:"date,omitempty"`
	PushedBy *IdentityRef `json:"pushedBy,omitempty"`
	PushId int32 `json:"pushId,omitempty"`
	Url string `json:"url,omitempty"`
}
