/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Criteria used in a search for change lists
type TfvcChangesetSearchCriteria struct {
	// Alias or display name of user who made the changes
	Author string `json:"author,omitempty"`
	// Whether or not to follow renames for the given item being queried
	FollowRenames bool `json:"followRenames,omitempty"`
	// If provided, only include changesets created after this date (string) Think of a better name for this.
	FromDate string `json:"fromDate,omitempty"`
	// If provided, only include changesets after this changesetID
	FromId int32 `json:"fromId,omitempty"`
	// Whether to include the _links field on the shallow references
	IncludeLinks bool `json:"includeLinks,omitempty"`
	// Path of item to search under
	ItemPath string `json:"itemPath,omitempty"`
	Mappings []TfvcMappingFilter `json:"mappings,omitempty"`
	// If provided, only include changesets created before this date (string) Think of a better name for this.
	ToDate string `json:"toDate,omitempty"`
	// If provided, a version descriptor for the latest change list to include
	ToId int32 `json:"toId,omitempty"`
}
