/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Provides properties that describe a Git commit and associated metadata.
type GitCommitRef struct {
	// A collection of related REST reference links.
	Links *ReferenceLinks `json:"_links,omitempty"`
	// Author of the commit.
	Author *GitUserDate `json:"author,omitempty"`
	// Counts of the types of changes (edits, deletes, etc.) included with the commit.
	ChangeCounts *ChangeCountDictionary `json:"changeCounts,omitempty"`
	// An enumeration of the changes included with the commit.
	Changes []GitChange `json:"changes,omitempty"`
	// Comment or message of the commit.
	Comment string `json:"comment,omitempty"`
	// Indicates if the comment is truncated from the full Git commit comment message.
	CommentTruncated bool `json:"commentTruncated,omitempty"`
	// ID (SHA-1) of the commit.
	CommitId string `json:"commitId,omitempty"`
	// Committer of the commit.
	Committer *GitUserDate `json:"committer,omitempty"`
	// An enumeration of the parent commit IDs for this commit.
	Parents []string `json:"parents,omitempty"`
	// The push associated with this commit.
	Push *GitPushRef `json:"push,omitempty"`
	// Remote URL path to the commit.
	RemoteUrl string `json:"remoteUrl,omitempty"`
	// A list of status metadata from services and extensions that may associate additional information to the commit.
	Statuses []GitStatus `json:"statuses,omitempty"`
	// REST URL for this resource.
	Url string `json:"url,omitempty"`
	// A list of workitems associated with this commit.
	WorkItems []ResourceRef `json:"workItems,omitempty"`
}
