/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Parameter for creating a git import request when source is tfvc version control
type GitImportTfvcSource struct {
	// Set true to import History, false otherwise
	ImportHistory bool `json:"importHistory,omitempty"`
	// Get history for last n days (max allowed value is 180 days)
	ImportHistoryDurationInDays int32 `json:"importHistoryDurationInDays,omitempty"`
	// Path which we want to import (this can be copied from Path Control in Explorer)
	Path string `json:"path,omitempty"`
}
