/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Policy type reference.
type PolicyTypeRef struct {
	// Display name of the policy type.
	DisplayName string `json:"displayName,omitempty"`
	// The policy type ID.
	Id string `json:"id,omitempty"`
	// The URL where the policy type can be retrieved.
	Url string `json:"url,omitempty"`
}
