/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// 
type GitPushSearchCriteria struct {
	FromDate time.Time `json:"fromDate,omitempty"`
	// Whether to include the _links field on the shallow references
	IncludeLinks bool `json:"includeLinks,omitempty"`
	IncludeRefUpdates bool `json:"includeRefUpdates,omitempty"`
	PusherId string `json:"pusherId,omitempty"`
	RefName string `json:"refName,omitempty"`
	ToDate time.Time `json:"toDate,omitempty"`
}
