/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Pull requests can be searched for matching this criteria.
type GitPullRequestSearchCriteria struct {
	// If set, search for pull requests that were created by this identity.
	CreatorId string `json:"creatorId,omitempty"`
	// Whether to include the _links field on the shallow references
	IncludeLinks bool `json:"includeLinks,omitempty"`
	// If set, search for pull requests whose target branch is in this repository.
	RepositoryId string `json:"repositoryId,omitempty"`
	// If set, search for pull requests that have this identity as a reviewer.
	ReviewerId string `json:"reviewerId,omitempty"`
	// If set, search for pull requests from this branch.
	SourceRefName string `json:"sourceRefName,omitempty"`
	// If set, search for pull requests whose source branch is in this repository.
	SourceRepositoryId string `json:"sourceRepositoryId,omitempty"`
	// If set, search for pull requests that are in this state. Defaults to Active if unset.
	Status string `json:"status,omitempty"`
	// If set, search for pull requests into this branch.
	TargetRefName string `json:"targetRefName,omitempty"`
}
