/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Parameter for creating a git import request when source is Git version control
type GitImportGitSource struct {
	// Tells if this is a sync request or not
	Overwrite bool `json:"overwrite,omitempty"`
	// Url for the source repo
	Url string `json:"url,omitempty"`
}
