/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type HistoryEntry struct {
	// The Change list (changeset/commit/shelveset) for this point in history
	ChangeList *ChangeList `json:"changeList,omitempty"`
	// The change made to the item from this change list (only relevant for File history, not folders)
	ItemChangeType string `json:"itemChangeType,omitempty"`
	// The path of the item at this point in history (only relevant for File history, not folders)
	ServerItem string `json:"serverItem,omitempty"`
}
