/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitItemDescriptor struct {
	// Path to item
	Path string `json:"path,omitempty"`
	// Specifies whether to include children (OneLevel), all descendants (Full), or None
	RecursionLevel string `json:"recursionLevel,omitempty"`
	// Version string (interpretation based on VersionType defined in subclass
	Version string `json:"version,omitempty"`
	// Version modifiers (e.g. previous)
	VersionOptions string `json:"versionOptions,omitempty"`
	// How to interpret version (branch,tag,commit)
	VersionType string `json:"versionType,omitempty"`
}
