/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Comment iteration context is used to identify which diff was being viewed when the thread was created.
type CommentIterationContext struct {
	// The iteration of the file on the left side of the diff when the thread was created. If this value is equal to SecondComparingIteration, then this version is the common commit between the source and target branches of the pull request.
	FirstComparingIteration int32 `json:"firstComparingIteration,omitempty"`
	// The iteration of the file on the right side of the diff when the thread was created.
	SecondComparingIteration int32 `json:"secondComparingIteration,omitempty"`
}
