/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Status context that uniquely identifies the status.
type GitStatusContext struct {
	// Genre of the status. Typically name of the service/tool generating the status, can be empty.
	Genre string `json:"genre,omitempty"`
	// Name identifier of the status, cannot be null or empty.
	Name string `json:"name,omitempty"`
}
