/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type TfvcLabelRequestData struct {
	// Whether to include the _links field on the shallow references
	IncludeLinks bool `json:"includeLinks,omitempty"`
	ItemLabelFilter string `json:"itemLabelFilter,omitempty"`
	LabelScope string `json:"labelScope,omitempty"`
	MaxItemCount int32 `json:"maxItemCount,omitempty"`
	Name string `json:"name,omitempty"`
	Owner string `json:"owner,omitempty"`
}
