/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Preferences about how the pull request should be completed.
type GitPullRequestCompletionOptions struct {
	// If true, policies will be explicitly bypassed while the pull request is completed.
	BypassPolicy bool `json:"bypassPolicy,omitempty"`
	// If policies are bypassed, this reason is stored as to why bypass was used.
	BypassReason string `json:"bypassReason,omitempty"`
	// If true, the source branch of the pull request will be deleted after completion.
	DeleteSourceBranch bool `json:"deleteSourceBranch,omitempty"`
	// If set, this will be used as the commit message of the merge commit.
	MergeCommitMessage string `json:"mergeCommitMessage,omitempty"`
	// If true, the commits in the pull request will be squash-merged into the specified target branch on completion.
	SquashMerge bool `json:"squashMerge,omitempty"`
	// If true, we will attempt to transition any work items linked to the pull request into the next logical state (i.e. Active -> Resolved)
	TransitionWorkItems bool `json:"transitionWorkItems,omitempty"`
	// If true, the current completion attempt was triggered via auto-complete. Used internally.
	TriggeredByAutoComplete bool `json:"triggeredByAutoComplete,omitempty"`
}
