/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Globally unique key for a repository.
type GlobalGitRepositoryKey struct {
	// Team Project Collection ID of the collection for the repository.
	CollectionId string `json:"collectionId,omitempty"`
	// Team Project ID of the project for the repository.
	ProjectId string `json:"projectId,omitempty"`
	// ID of the repository.
	RepositoryId string `json:"repositoryId,omitempty"`
}
