/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitTargetVersionDescriptor struct {
	// Version string identifier (name of tag/branch, SHA1 of commit)
	Version string `json:"version,omitempty"`
	// Version options - Specify additional modifiers to version (e.g Previous)
	VersionOptions string `json:"versionOptions,omitempty"`
	// Version type (branch, tag, or commit). Determines how Id is interpreted
	VersionType string `json:"versionType,omitempty"`
}
