/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitItemRequestData struct {
	// Whether to include metadata for all items
	IncludeContentMetadata bool `json:"includeContentMetadata,omitempty"`
	// Whether to include the _links field on the shallow references
	IncludeLinks bool `json:"includeLinks,omitempty"`
	// Collection of items to fetch, including path, version, and recursion level
	ItemDescriptors []GitItemDescriptor `json:"itemDescriptors,omitempty"`
	// Whether to include shallow ref to commit that last changed each item
	LatestProcessedChange bool `json:"latestProcessedChange,omitempty"`
}
