/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// This is the deep shelveset class
type TfvcShelveset struct {
	Links *ReferenceLinks `json:"_links,omitempty"`
	Comment string `json:"comment,omitempty"`
	CommentTruncated bool `json:"commentTruncated,omitempty"`
	CreatedDate time.Time `json:"createdDate,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Owner *IdentityRef `json:"owner,omitempty"`
	Url string `json:"url,omitempty"`
}
