/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type TfvcMergeSource struct {
	// Indicates if this a rename source. If false, it is a merge source.
	IsRename bool `json:"isRename,omitempty"`
	// The server item of the merge source
	ServerItem string `json:"serverItem,omitempty"`
	// Start of the version range
	VersionFrom int32 `json:"versionFrom,omitempty"`
	// End of the version range
	VersionTo int32 `json:"versionTo,omitempty"`
}
