/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitPushEventData struct {
	AfterId string `json:"afterId,omitempty"`
	BeforeId string `json:"beforeId,omitempty"`
	Branch string `json:"branch,omitempty"`
	Commits []GitCommit `json:"commits,omitempty"`
	Repository *GitRepository `json:"repository,omitempty"`
}
