/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Represents all the data associated with a pull request.
type GitPullRequest struct {
	// Links to other related objects.
	Links *ReferenceLinks `json:"_links,omitempty"`
	// A string which uniquely identifies this pull request. To generate an artifact ID for a pull request, use this template: ```vstfs:///Git/PullRequestId/{projectId}/{repositoryId}/{pullRequestId}```
	ArtifactId string `json:"artifactId,omitempty"`
	// If set, auto-complete is enabled for this pull request and this is the identity that enabled it.
	AutoCompleteSetBy *IdentityRef `json:"autoCompleteSetBy,omitempty"`
	// The user who closed the pull request.
	ClosedBy *IdentityRef `json:"closedBy,omitempty"`
	// The date when the pull request was closed (completed, abandoned, or merged externally).
	ClosedDate time.Time `json:"closedDate,omitempty"`
	// The code review ID of the pull request. Used internally.
	CodeReviewId int32 `json:"codeReviewId,omitempty"`
	// The commits contained in the pull request.
	Commits []GitCommitRef `json:"commits,omitempty"`
	// Options which affect how the pull request will be merged when it is completed.
	CompletionOptions *GitPullRequestCompletionOptions `json:"completionOptions,omitempty"`
	// The most recent date at which the pull request entered the queue to be completed. Used internally.
	CompletionQueueTime time.Time `json:"completionQueueTime,omitempty"`
	// The identity of the user who created the pull request.
	CreatedBy *IdentityRef `json:"createdBy,omitempty"`
	// The date when the pull request was created.
	CreationDate time.Time `json:"creationDate,omitempty"`
	// The description of the pull request.
	Description string `json:"description,omitempty"`
	// If this is a PR from a fork this will contain information about its source.
	ForkSource *GitForkRef `json:"forkSource,omitempty"`
	// The labels associated with the pull request.
	Labels []WebApiTagDefinition `json:"labels,omitempty"`
	// The commit of the most recent pull request merge. If empty, the most recent merge is in progress or was unsuccessful.
	LastMergeCommit *GitCommitRef `json:"lastMergeCommit,omitempty"`
	// The commit at the head of the source branch at the time of the last pull request merge.
	LastMergeSourceCommit *GitCommitRef `json:"lastMergeSourceCommit,omitempty"`
	// The commit at the head of the target branch at the time of the last pull request merge.
	LastMergeTargetCommit *GitCommitRef `json:"lastMergeTargetCommit,omitempty"`
	// If set, pull request merge failed for this reason.
	MergeFailureMessage string `json:"mergeFailureMessage,omitempty"`
	// The type of failure (if any) of the pull request merge.
	MergeFailureType string `json:"mergeFailureType,omitempty"`
	// The ID of the job used to run the pull request merge. Used internally.
	MergeId string `json:"mergeId,omitempty"`
	// Options used when the pull request merge runs. These are separate from completion options since completion happens only once and a new merge will run every time the source branch of the pull request changes.
	MergeOptions *GitPullRequestMergeOptions `json:"mergeOptions,omitempty"`
	// The current status of the pull request merge.
	MergeStatus string `json:"mergeStatus,omitempty"`
	// The ID of the pull request.
	PullRequestId int32 `json:"pullRequestId,omitempty"`
	// Used internally.
	RemoteUrl string `json:"remoteUrl,omitempty"`
	// The repository containing the target branch of the pull request.
	Repository *GitRepository `json:"repository,omitempty"`
	// A list of reviewers on the pull request along with the state of their votes.
	Reviewers []IdentityRefWithVote `json:"reviewers,omitempty"`
	// The name of the source branch of the pull request.
	SourceRefName string `json:"sourceRefName,omitempty"`
	// The status of the pull request.
	Status string `json:"status,omitempty"`
	// If true, this pull request supports multiple iterations. Iteration support means individual pushes to the source branch of the pull request can be reviewed and comments left in one iteration will be tracked across future iterations.
	SupportsIterations bool `json:"supportsIterations,omitempty"`
	// The name of the target branch of the pull request.
	TargetRefName string `json:"targetRefName,omitempty"`
	// The title of the pull request.
	Title string `json:"title,omitempty"`
	// Used internally.
	Url string `json:"url,omitempty"`
	// Any work item references associated with this pull request.
	WorkItemRefs []ResourceRef `json:"workItemRefs,omitempty"`
}
