/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Git object identifier and type information.
type GitObject struct {
	// Object Id (Sha1Id).
	ObjectId string `json:"objectId,omitempty"`
	// Type of object (Commit, Tree, Blob, Tag)
	ObjectType string `json:"objectType,omitempty"`
}
