/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitLastChangeItem struct {
	// Gets or sets the commit Id this item was modified most recently for the provided version.
	CommitId string `json:"commitId,omitempty"`
	// Gets or sets the path of the item.
	Path string `json:"path,omitempty"`
}
