/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type Change struct {
	// The type of change that was made to the item.
	ChangeType string `json:"changeType,omitempty"`
	// Current version.
	Item string `json:"item,omitempty"`
	// Content of the item after the change.
	NewContent *ItemContent `json:"newContent,omitempty"`
	// Path of the item on the server.
	SourceServerItem string `json:"sourceServerItem,omitempty"`
	// URL to retrieve the item.
	Url string `json:"url,omitempty"`
}
