/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A Git annotated tag.
type GitAnnotatedTag struct {
	// The tagging Message
	Message string `json:"message,omitempty"`
	// The name of the annotated tag.
	Name string `json:"name,omitempty"`
	// The objectId (Sha1Id) of the tag.
	ObjectId string `json:"objectId,omitempty"`
	// User info and date of tagging.
	TaggedBy *GitUserDate `json:"taggedBy,omitempty"`
	// Tagged git object.
	TaggedObject *GitObject `json:"taggedObject,omitempty"`
	Url string `json:"url,omitempty"`
}
