/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type TfvcChangesetsRequestData struct {
	// List of changeset Ids.
	ChangesetIds []int32 `json:"changesetIds,omitempty"`
	// Length of the comment.
	CommentLength int32 `json:"commentLength,omitempty"`
	// Whether to include the _links field on the shallow references
	IncludeLinks bool `json:"includeLinks,omitempty"`
}
