/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type TfvcBranchMapping struct {
	// Depth of the branch.
	Depth string `json:"depth,omitempty"`
	// Server item for the branch.
	ServerItem string `json:"serverItem,omitempty"`
	// Type of the branch.
	Type_ string `json:"type,omitempty"`
}
