/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Represents a comment thread of a pull request. A thread contains meta data about the file it was left on (if any) along with one or more comments (an initial comment and the subsequent replies).
type GitPullRequestCommentThread struct {
	// Links to other related objects.
	Links *ReferenceLinks `json:"_links,omitempty"`
	// A list of the comments.
	Comments []Comment `json:"comments,omitempty"`
	// The comment thread id.
	Id int32 `json:"id,omitempty"`
	// Set of identities related to this thread
	Identities map[string]IdentityRef `json:"identities,omitempty"`
	// Specify if the thread is deleted which happens when all comments are deleted.
	IsDeleted bool `json:"isDeleted,omitempty"`
	// The time this thread was last updated.
	LastUpdatedDate time.Time `json:"lastUpdatedDate,omitempty"`
	// Optional properties associated with the thread as a collection of key-value pairs.
	Properties *PropertiesCollection `json:"properties,omitempty"`
	// The time this thread was published.
	PublishedDate time.Time `json:"publishedDate,omitempty"`
	// The status of the comment thread.
	Status string `json:"status,omitempty"`
	// Specify thread context such as position in left/right file.
	ThreadContext *CommentThreadContext `json:"threadContext,omitempty"`
}
