/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type AssociatedWorkItem struct {
	AssignedTo string `json:"assignedTo,omitempty"`
	// Id of associated the work item.
	Id int32 `json:"id,omitempty"`
	State string `json:"state,omitempty"`
	Title string `json:"title,omitempty"`
	// REST Url of the work item.
	Url string `json:"url,omitempty"`
	WebUrl string `json:"webUrl,omitempty"`
	WorkItemType string `json:"workItemType,omitempty"`
}
