/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitRepositoryRef struct {
	// Team Project Collection where this Fork resides
	Collection *TeamProjectCollectionReference `json:"collection,omitempty"`
	Id string `json:"id,omitempty"`
	// True if the repository was created as a fork
	IsFork bool `json:"isFork,omitempty"`
	Name string `json:"name,omitempty"`
	Project *TeamProjectReference `json:"project,omitempty"`
	RemoteUrl string `json:"remoteUrl,omitempty"`
	SshUrl string `json:"sshUrl,omitempty"`
	Url string `json:"url,omitempty"`
}
