/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type TfvcShelvesetRequestData struct {
	// Whether to include policyOverride and notes Only applies when requesting a single deep shelveset
	IncludeDetails bool `json:"includeDetails,omitempty"`
	// Whether to include the _links field on the shallow references. Does not apply when requesting a single deep shelveset object. Links will always be included in the deep shelveset.
	IncludeLinks bool `json:"includeLinks,omitempty"`
	// Whether to include workItems
	IncludeWorkItems bool `json:"includeWorkItems,omitempty"`
	// Max number of changes to include
	MaxChangeCount int32 `json:"maxChangeCount,omitempty"`
	// Max length of comment
	MaxCommentLength int32 `json:"maxCommentLength,omitempty"`
	// Shelveset's name
	Name string `json:"name,omitempty"`
	// Owner's ID. Could be a name or a guid.
	Owner string `json:"owner,omitempty"`
}
