/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type SourceToTargetRef struct {
	// The source ref to copy. For example, refs/heads/master.
	SourceRef string `json:"sourceRef,omitempty"`
	// The target ref to update. For example, refs/heads/master.
	TargetRef string `json:"targetRef,omitempty"`
}
