/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitRecycleBinRepositoryDetails struct {
	// Setting to false will undo earlier deletion and restore the repository.
	Deleted bool `json:"deleted,omitempty"`
}
