/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Initial config contract sent to extensions creating tabs on the pull request page
type PullRequestTabExtensionConfig struct {
	PullRequestId int32 `json:"pullRequestId,omitempty"`
	RepositoryId string `json:"repositoryId,omitempty"`
}
