/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The class to represent a collection of REST reference links.
type ReferenceLinks struct {
	// The readonly view of the links.  Because Reference links are readonly, we only want to expose them as read only.
	Links map[string]interface{} `json:"links,omitempty"`
}
