/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Represents a comment which is one of potentially many in a comment thread.
type Comment struct {
	// Links to other related objects.
	Links *ReferenceLinks `json:"_links,omitempty"`
	// The author of the comment.
	Author *IdentityRef `json:"author,omitempty"`
	// The comment type at the time of creation.
	CommentType string `json:"commentType,omitempty"`
	// The comment content.
	Content string `json:"content,omitempty"`
	// The comment ID. IDs start at 1 and are unique to a pull request.
	Id int32 `json:"id,omitempty"`
	// Whether or not this comment was soft-deleted.
	IsDeleted bool `json:"isDeleted,omitempty"`
	// The date the comment's content was last updated.
	LastContentUpdatedDate time.Time `json:"lastContentUpdatedDate,omitempty"`
	// The date the comment was last updated.
	LastUpdatedDate time.Time `json:"lastUpdatedDate,omitempty"`
	// The ID of the parent comment. This is used for replies.
	ParentCommentId int32 `json:"parentCommentId,omitempty"`
	// The date the comment was first published.
	PublishedDate time.Time `json:"publishedDate,omitempty"`
	// A list of the users who have liked this comment.
	UsersLiked []IdentityRef `json:"usersLiked,omitempty"`
}
