/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type FileContentMetadata struct {
	ContentType string `json:"contentType,omitempty"`
	Encoding int32 `json:"encoding,omitempty"`
	Extension string `json:"extension,omitempty"`
	FileName string `json:"fileName,omitempty"`
	IsBinary bool `json:"isBinary,omitempty"`
	IsImage bool `json:"isImage,omitempty"`
	VsLink string `json:"vsLink,omitempty"`
}
