/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Item path and Version descriptor properties
type TfvcItemDescriptor struct {
	Path string `json:"path,omitempty"`
	RecursionLevel string `json:"recursionLevel,omitempty"`
	Version string `json:"version,omitempty"`
	VersionOption string `json:"versionOption,omitempty"`
	VersionType string `json:"versionType,omitempty"`
}
