/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// An object describing the git suggestion.  Git suggestions are currently limited to suggested pull requests.
type GitSuggestion struct {
	// Specific properties describing the suggestion.
	Properties map[string]interface{} `json:"properties,omitempty"`
	// The type of suggestion (e.g. pull request).
	Type_ string `json:"type,omitempty"`
}
