/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The representation of a tag definition which is sent across the wire.
type WebApiTagDefinition struct {
	// Whether or not the tag definition is active.
	Active bool `json:"active,omitempty"`
	// ID of the tag definition.
	Id string `json:"id,omitempty"`
	// The name of the tag definition.
	Name string `json:"name,omitempty"`
	// Resource URL for the Tag Definition.
	Url string `json:"url,omitempty"`
}
