/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type CommentThreadContext struct {
	// File path relative to the root of the repository. It's up to the client to use any path format.
	FilePath string `json:"filePath,omitempty"`
	// Position of last character of the thread's span in left file.
	LeftFileEnd *CommentPosition `json:"leftFileEnd,omitempty"`
	// Position of first character of the thread's span in left file.
	LeftFileStart *CommentPosition `json:"leftFileStart,omitempty"`
	// Position of last character of the thread's span in right file.
	RightFileEnd *CommentPosition `json:"rightFileEnd,omitempty"`
	// Position of first character of the thread's span in right file.
	RightFileStart *CommentPosition `json:"rightFileStart,omitempty"`
}
