/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Meta data for a file attached to an artifact.
type Attachment struct {
	// Links to other related objects.
	Links *ReferenceLinks `json:"_links,omitempty"`
	// The person that uploaded this attachment.
	Author *IdentityRef `json:"author,omitempty"`
	// Content hash of on-disk representation of file content. Its calculated by the server by using SHA1 hash function.
	ContentHash string `json:"contentHash,omitempty"`
	// The time the attachment was uploaded.
	CreatedDate time.Time `json:"createdDate,omitempty"`
	// The description of the attachment.
	Description string `json:"description,omitempty"`
	// The display name of the attachment. Can't be null or empty.
	DisplayName string `json:"displayName,omitempty"`
	// Id of the attachment.
	Id int32 `json:"id,omitempty"`
	// Extended properties.
	Properties *PropertiesCollection `json:"properties,omitempty"`
	// The url to download the content of the attachment.
	Url string `json:"url,omitempty"`
}
