/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Information about the progress of a cherry pick or revert operation.
type GitAsyncRefOperationDetail struct {
	// Indicates if there was a conflict generated when trying to cherry pick or revert the changes.
	Conflict bool `json:"conflict,omitempty"`
	// The current commit from the list of commits that are being cherry picked or reverted.
	CurrentCommitId string `json:"currentCommitId,omitempty"`
	// Detailed information about why the cherry pick or revert failed to complete.
	FailureMessage string `json:"failureMessage,omitempty"`
	// A number between 0 and 1 indicating the percent complete of the operation.
	Progress float64 `json:"progress,omitempty"`
	// Provides a status code that indicates the reason the cherry pick or revert failed.
	Status string `json:"status,omitempty"`
	// Indicates if the operation went beyond the maximum time allowed for a cherry pick or revert operation.
	Timedout bool `json:"timedout,omitempty"`
}
