/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type VersionControlProjectInfo struct {
	DefaultSourceControlType string `json:"defaultSourceControlType,omitempty"`
	Project *TeamProjectReference `json:"project,omitempty"`
	SupportsGit bool `json:"supportsGit,omitempty"`
	SupportsTFVC bool `json:"supportsTFVC,omitempty"`
}
