/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitRefFavorite struct {
	Links *ReferenceLinks `json:"_links,omitempty"`
	Id int32 `json:"id,omitempty"`
	IdentityId string `json:"identityId,omitempty"`
	Name string `json:"name,omitempty"`
	RepositoryId string `json:"repositoryId,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
}
