/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// 
type IncludedGitCommit struct {
	CommitId string `json:"commitId,omitempty"`
	CommitTime time.Time `json:"commitTime,omitempty"`
	ParentCommitIds []string `json:"parentCommitIds,omitempty"`
	RepositoryId string `json:"repositoryId,omitempty"`
}
