/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitCommitToCreate struct {
	BaseRef *GitRef `json:"baseRef,omitempty"`
	Comment string `json:"comment,omitempty"`
	PathActions []GitPathAction `json:"pathActions,omitempty"`
}
