/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitCommitDiffs struct {
	AheadCount int32 `json:"aheadCount,omitempty"`
	AllChangesIncluded bool `json:"allChangesIncluded,omitempty"`
	BaseCommit string `json:"baseCommit,omitempty"`
	BehindCount int32 `json:"behindCount,omitempty"`
	ChangeCounts map[string]int32 `json:"changeCounts,omitempty"`
	Changes []GitChange `json:"changes,omitempty"`
	CommonCommit string `json:"commonCommit,omitempty"`
	TargetCommit string `json:"targetCommit,omitempty"`
}
