/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The options which are used when a pull request merge is created.
type GitPullRequestMergeOptions struct {
	DetectRenameFalsePositives bool `json:"detectRenameFalsePositives,omitempty"`
	// If true, rename detection will not be performed during the merge.
	DisableRenames bool `json:"disableRenames,omitempty"`
}
