/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitQueryRefsCriteria struct {
	// List of commit Ids to be searched
	CommitIds []string `json:"commitIds,omitempty"`
	// List of complete or partial names for refs to be searched
	RefNames []string `json:"refNames,omitempty"`
	// Type of search on refNames, if provided
	SearchType string `json:"searchType,omitempty"`
}
