/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The representation of data needed to create a tag definition which is sent across the wire.
type WebApiCreateTagRequestData struct {
	// Name of the tag definition that will be created.
	Name string `json:"name,omitempty"`
}
