/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Reference object for a TeamProjectCollection.
type TeamProjectCollectionReference struct {
	// Collection Id.
	Id string `json:"id,omitempty"`
	// Collection Name.
	Name string `json:"name,omitempty"`
	// Collection REST Url.
	Url string `json:"url,omitempty"`
}
