/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Collection of changes made in a pull request.
type GitPullRequestIterationChanges struct {
	// Changes made in the iteration.
	ChangeEntries []GitPullRequestChange `json:"changeEntries,omitempty"`
	// Value to specify as skip to get the next page of changes.  This will be zero if there are no more changes.
	NextSkip int32 `json:"nextSkip,omitempty"`
	// Value to specify as top to get the next page of changes.  This will be zero if there are no more changes.
	NextTop int32 `json:"nextTop,omitempty"`
}
