/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// 
type GitDeletedRepository struct {
	CreatedDate time.Time `json:"createdDate,omitempty"`
	DeletedBy *IdentityRef `json:"deletedBy,omitempty"`
	DeletedDate time.Time `json:"deletedDate,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Project *TeamProjectReference `json:"project,omitempty"`
}
