/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Ahead and behind counts for a particular ref.
type GitBranchStats struct {
	// Number of commits ahead.
	AheadCount int32 `json:"aheadCount,omitempty"`
	// Number of commits behind.
	BehindCount int32 `json:"behindCount,omitempty"`
	// Current commit.
	Commit *GitCommitRef `json:"commit,omitempty"`
	// True if this is the result for the base version.
	IsBaseVersion bool `json:"isBaseVersion,omitempty"`
	// Name of the ref.
	Name string `json:"name,omitempty"`
}
