/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// This object is returned from Cherry Pick operations and provides the id and status of the operation
type GitCherryPick struct {
	Links *ReferenceLinks `json:"_links,omitempty"`
	DetailedStatus *GitAsyncRefOperationDetail `json:"detailedStatus,omitempty"`
	Parameters *GitAsyncRefOperationParameters `json:"parameters,omitempty"`
	Status string `json:"status,omitempty"`
	// A URL that can be used to make further requests for status about the operation
	Url string `json:"url,omitempty"`
}
