/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitTreeDiffResponse struct {
	// The HTTP client methods find the continuation token header in the response and populate this field.
	ContinuationToken []string `json:"continuationToken,omitempty"`
	TreeDiff *GitTreeDiff `json:"treeDiff,omitempty"`
}
