/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitItem struct {
	Links *ReferenceLinks `json:"_links,omitempty"`
	Content string `json:"content,omitempty"`
	ContentMetadata *FileContentMetadata `json:"contentMetadata,omitempty"`
	IsFolder bool `json:"isFolder,omitempty"`
	IsSymLink bool `json:"isSymLink,omitempty"`
	Path string `json:"path,omitempty"`
	Url string `json:"url,omitempty"`
}
