/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A request to import data from a remote source control system.
type GitImportRequest struct {
	// Links to related resources.
	Links *ReferenceLinks `json:"_links,omitempty"`
	// Detailed status of the import, including the current step and an error message, if applicable.
	DetailedStatus *GitImportStatusDetail `json:"detailedStatus,omitempty"`
	// The unique identifier for this import request.
	ImportRequestId int32 `json:"importRequestId,omitempty"`
	// Parameters for creating the import request.
	Parameters *GitImportRequestParameters `json:"parameters,omitempty"`
	// The target repository for this import.
	Repository *GitRepository `json:"repository,omitempty"`
	// Current status of the import.
	Status string `json:"status,omitempty"`
	// A link back to this import request resource.
	Url string `json:"url,omitempty"`
}
