/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitTreeDiffEntry struct {
	// SHA1 hash of the object in the base tree, if it exists. Will be null in case of adds.
	BaseObjectId string `json:"baseObjectId,omitempty"`
	// Type of change that affected this entry.
	ChangeType string `json:"changeType,omitempty"`
	// Object type of the tree entry. Blob, Tree or Commit(\"submodule\")
	ObjectType string `json:"objectType,omitempty"`
	// Relative path in base and target trees.
	Path string `json:"path,omitempty"`
	// SHA1 hash of the object in the target tree, if it exists. Will be null in case of deletes.
	TargetObjectId string `json:"targetObjectId,omitempty"`
}
