/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type TfvcItemRequestData struct {
	// If true, include metadata about the file type
	IncludeContentMetadata bool `json:"includeContentMetadata,omitempty"`
	// Whether to include the _links field on the shallow references
	IncludeLinks bool `json:"includeLinks,omitempty"`
	ItemDescriptors []TfvcItemDescriptor `json:"itemDescriptors,omitempty"`
}
