/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Optional details to include when returning an item model
type ItemDetailsOptions struct {
	// If true, include metadata about the file type
	IncludeContentMetadata bool `json:"includeContentMetadata,omitempty"`
	// Specifies whether to include children (OneLevel), all descendants (Full) or None for folder items
	RecursionLevel string `json:"recursionLevel,omitempty"`
}
