/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Pull request query input parameters.
type GitPullRequestQueryInput struct {
	// The list of commit IDs to search for.
	Items []string `json:"items,omitempty"`
	// The type of query to perform.
	Type_ string `json:"type,omitempty"`
}
