/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Criteria used in a search for change lists
type ChangeListSearchCriteria struct {
	// If provided, a version descriptor to compare against base
	CompareVersion string `json:"compareVersion,omitempty"`
	// If true, don't include delete history entries
	ExcludeDeletes bool `json:"excludeDeletes,omitempty"`
	// Whether or not to follow renames for the given item being queried
	FollowRenames bool `json:"followRenames,omitempty"`
	// If provided, only include history entries created after this date (string)
	FromDate string `json:"fromDate,omitempty"`
	// If provided, a version descriptor for the earliest change list to include
	FromVersion string `json:"fromVersion,omitempty"`
	// Path of item to search under. If the itemPaths memebr is used then it will take precedence over this.
	ItemPath string `json:"itemPath,omitempty"`
	// List of item paths to search under. If this member is used then itemPath will be ignored.
	ItemPaths []string `json:"itemPaths,omitempty"`
	// Version of the items to search
	ItemVersion string `json:"itemVersion,omitempty"`
	// Number of results to skip (used when clicking more...)
	Skip int32 `json:"skip,omitempty"`
	// If provided, only include history entries created before this date (string)
	ToDate string `json:"toDate,omitempty"`
	// If provided, the maximum number of history entries to return
	Top int32 `json:"top,omitempty"`
	// If provided, a version descriptor for the latest change list to include
	ToVersion string `json:"toVersion,omitempty"`
	// Alias or display name of user who made the changes
	User string `json:"user,omitempty"`
}
