/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitPathAction struct {
	Action string `json:"action,omitempty"`
	Base64Content string `json:"base64Content,omitempty"`
	Path string `json:"path,omitempty"`
	RawTextContent string `json:"rawTextContent,omitempty"`
	TargetPath string `json:"targetPath,omitempty"`
}
