/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitRepositoryCreateOptions struct {
	Name string `json:"name,omitempty"`
	ParentRepository *GitRepositoryRef `json:"parentRepository,omitempty"`
	Project *TeamProjectReference `json:"project,omitempty"`
}
