/*
 * Git
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.0-preview
 * Contact: nugetvss@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type GitRepositoryStats struct {
	ActivePullRequestsCount int32 `json:"activePullRequestsCount,omitempty"`
	BranchesCount int32 `json:"branchesCount,omitempty"`
	CommitsCount int32 `json:"commitsCount,omitempty"`
	RepositoryId string `json:"repositoryId,omitempty"`
}
